name: Java CI

on:
  push:
    branches: [ main ]  # 当 main 分支有代码推送时触发

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2  # 获取代码
      - name: Set up JDK 11  # 设置 JDK 版本
        uses: actions/setup-java@v2
        with:
          java-version: '11'
      - name: Build with Maven  # 使用 Maven 构建
        run: mvn clean package --file pom.xml
      - name: Run tests  # 运行测试
        run: mvn test --file pom.xml
      - name: Upload test results  # 上传测试报告
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: target/surefire-reports  # 指定测试报告路径
